const data = {
  candidates: [
    {
      name: "Amit Kumar",
      profile_picture_url: "https://i.imgur.com/DTfowdu.jpg",
      video_urls: [
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      ],
      total_score_percentage: 70,
      behavioral_scores: 7,
      communication: 9,
      situation_handling: 5,
      shortlisted: true,
      email: "amit@example.com",
      about: "I am an enthusiastic individual with a passion for sales. I have a keen eye for detail and enjoy working in a dynamic environment.",
      experience: "3 years of experience in sales and customer service.",
      hobbies: "Hiking, reading, and playing guitar.",
      introduction: "I am an enthusiastic individual with a passion for sales. I have a keen eye for detail and enjoy working in a dynamic environment.",

    },
    {
      name: "Ritik Jha",
      profile_picture_url: "https://i.imgur.com/yhW6Yw1.jpg",
      video_urls: [
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      ],
      total_score_percentage: 85,
      behavioral_scores: 8,
      communication: 6,
      situation_handling: 8,
      shortlisted: false,
      email: "ritik@example.com",
      about: "I am a dedicated professional with a strong background in marketing. I thrive in fast-paced environments and excel at building relationships with clients.",
      experience: "5 years of experience in marketing and advertising.",
      hobbies: "Cooking, traveling, and playing soccer.",
      introduction: "I am an enthusiastic individual with a passion for sales. I have a keen eye for detail and enjoy working in a dynamic environment.",

    },
    {
      name: "Tushar Singh",
      profile_picture_url: "https://api.escuelajs.co/api/v1/files/9ea4.jpg",
      video_urls: [
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      ],
      total_score_percentage: 80,
      behavioral_scores: 9,
      communication: 7,
      situation_handling: 6,
      shortlisted: true,
      email: "tushar@example.com",
      about: "I am a highly motivated individual with a background in technology. I enjoy problem-solving and collaborating with others to achieve goals.",
      experience: "4 years of experience in software development.",
      hobbies: "Playing video games, coding, and watching movies.",
      introduction: "I am an enthusiastic individual with a passion for sales. I have a keen eye for detail and enjoy working in a dynamic environment.",

    },
    // Add similar information for other candidates
    {
      name: "Amit Kumar",
      profile_picture_url: "https://i.imgur.com/DTfowdu.jpg",
      video_urls: [
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      ],
      total_score_percentage: 70,
      behavioral_scores: 7,
      communication: 9,
      situation_handling: 5,
      shortlisted: false,
      email: "amit@example.com",
      about: "I am an enthusiastic individual with a passion for sales. I have a keen eye for detail and enjoy working in a dynamic environment.",
      experience: "3 years of experience in sales and customer service.",
      hobbies: "Hiking, reading, and playing guitar.",
      introduction: "I am an enthusiastic individual with a passion for sales. I have a keen eye for detail and enjoy working in a dynamic environment.",

    },
    {
      name: "Ritik Jha",
      profile_picture_url: "https://i.imgur.com/yhW6Yw1.jpg",
      video_urls: [
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      ],
      total_score_percentage: 85,
      behavioral_scores: 8,
      communication: 6,
      situation_handling: 8,
      shortlisted: false,
      email: "ritik@example.com",
      about: "I am a dedicated professional with a strong background in marketing. I thrive in fast-paced environments and excel at building relationships with clients.",
      experience: "5 years of experience in marketing and advertising.",
      hobbies: "Cooking, traveling, and playing soccer.",
      introduction: "I am an enthusiastic individual with a passion for sales. I have a keen eye for detail and enjoy working in a dynamic environment.",

    },
    {
      name: "Tushar Singh",
      profile_picture_url: "https://api.escuelajs.co/api/v1/files/9ea4.jpg",
      video_urls: [
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      ],
      total_score_percentage: 80,
      behavioral_scores: 9,
      communication: 7,
      situation_handling: 6,
      shortlisted: true,
      email: "tushar@example.com",
      about: "I am a highly motivated individual with a background in technology. I enjoy problem-solving and collaborating with others to achieve goals.",
      experience: "4 years of experience in software development.",
      hobbies: "Playing video games, coding, and watching movies.",
      introduction: "I am an enthusiastic individual with a passion for sales. I have a keen eye for detail and enjoy working in a dynamic environment.",

    },
    // Add similar information for other candidates
    {
      name: "Amit Kumar",
      profile_picture_url: "https://i.imgur.com/DTfowdu.jpg",
      video_urls: [
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      ],
      total_score_percentage: 70,
      behavioral_scores: 7,
      communication: 9,
      situation_handling: 5,
      shortlisted: true,
      email: "amit@example.com",
      about: "I am an enthusiastic individual with a passion for sales. I have a keen eye for detail and enjoy working in a dynamic environment.",
      experience: "3 years of experience in sales and customer service.",
      hobbies: "Hiking, reading, and playing guitar.",
      introduction: "I am an enthusiastic individual with a passion for sales. I have a keen eye for detail and enjoy working in a dynamic environment.",

    },
    {
      name: "Ritik Jha",
      profile_picture_url: "https://i.imgur.com/yhW6Yw1.jpg",
      video_urls: [
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      ],
      total_score_percentage: 85,
      behavioral_scores: 8,
      communication: 6,
      situation_handling: 8,
      shortlisted: true,
      email: "ritik@example.com",
      about: "I am a dedicated professional with a strong background in marketing. I thrive in fast-paced environments and excel at building relationships with clients.",
      experience: "5 years of experience in marketing and advertising.",
      hobbies: "Cooking, traveling, and playing soccer.",
      introduction: "I am an enthusiastic individual with a passion for sales. I have a keen eye for detail and enjoy working in a dynamic environment.",

    },
    {
      name: "Tushar Singh",
      profile_picture_url: "https://api.escuelajs.co/api/v1/files/9ea4.jpg",
      video_urls: [
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      ],
      total_score_percentage: 80,
      behavioral_scores: 9,
      communication: 7,
      situation_handling: 6,
      shortlisted: true,
      email: "tushar@example.com",
      about: "I am a highly motivated individual with a background in technology. I enjoy problem-solving and collaborating with others to achieve goals.",
      experience: "4 years of experience in software development.",
      hobbies: "Playing video games, coding, and watching movies.",
      introduction: "I am an enthusiastic individual with a passion for sales. I have a keen eye for detail and enjoy working in a dynamic environment.",

    },
    // Add similar information for other candidates
    {
      name: "Amit Kumar",
      profile_picture_url: "https://i.imgur.com/DTfowdu.jpg",
      video_urls: [
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      ],
      total_score_percentage: 70,
      behavioral_scores: 7,
      communication: 9,
      situation_handling: 5,
      shortlisted: false,
      email: "amit@example.com",
      about: "I am an enthusiastic individual with a passion for sales. I have a keen eye for detail and enjoy working in a dynamic environment.",
      experience: "3 years of experience in sales and customer service.",
      hobbies: "Hiking, reading, and playing guitar.",
      introduction: "I am an enthusiastic individual with a passion for sales. I have a keen eye for detail and enjoy working in a dynamic environment.",

    },
    {
      name: "Ritik Jha",
      profile_picture_url: "https://i.imgur.com/yhW6Yw1.jpg",
      video_urls: [
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      ],
      total_score_percentage: 85,
      behavioral_scores: 8,
      communication: 6,
      situation_handling: 8,
      shortlisted: true,
      email: "ritik@example.com",
      about: "I am a dedicated professional with a strong background in marketing. I thrive in fast-paced environments and excel at building relationships with clients.",
      experience: "5 years of experience in marketing and advertising.",
      hobbies: "Cooking, traveling, and playing soccer.",
      introduction: "I am an enthusiastic individual with a passion for sales. I have a keen eye for detail and enjoy working in a dynamic environment.",

    },
    {
      name: "Tushar Singh",
      profile_picture_url: "https://api.escuelajs.co/api/v1/files/9ea4.jpg",
      video_urls: [
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      ],
      total_score_percentage: 80,
      behavioral_scores: 9,
      communication: 7,
      situation_handling: 6,
      shortlisted: true,
      email: "tushar@example.com",
      about: "I am a highly motivated individual with a background in technology. I enjoy problem-solving and collaborating with others to achieve goals.",
      experience: "4 years of experience in software development.",
      hobbies: "Playing video games, coding, and watching movies.",
      introduction: "I am an enthusiastic individual with a passion for sales. I have a keen eye for detail and enjoy working in a dynamic environment.",

    },
    // Add similar information for other candidates
  
  ]
};

export default data;
